ckpt_dir: /cache/liluchen/FastA2V/ckpts
output_dir: /cache/liluchen/FastA2V/runs/ovi_dense_720x720_5s_50step

model_name: "720x720_5s"
mode: "t2v"
video_frame_height_width: [720, 720]
sample_steps: 50
solver_name: "unipc"
shift: 5.0
sp_size: 1

audio_guidance_scale: 3.0
video_guidance_scale: 4.0
slg_layer: 11
video_negative_prompt: "jitter, bad hands, blur, distortion"
audio_negative_prompt: "robotic, muffled, echo, distorted"

fp8: false
qint8: false
cpu_offload: false
seed: 103
text_prompt: prompts/ovi_smoke.csv
each_example_n_times: 1

attention_method: "dense"
use_cfg_cache: false
use_block_cache: false
debug_forward: false
debug_forward_step: 0

