#!/usr/bin/env bash

export FASTA2V_CACHE_ROOT="${FASTA2V_CACHE_ROOT:-/cache/liluchen/FastA2V}"
export FASTA2V_LTX2_ENV="${FASTA2V_LTX2_ENV:-${FASTA2V_CACHE_ROOT}/envs/ltx2}"
export FASTA2V_LTX2_SOURCE="${FASTA2V_LTX2_SOURCE:-${FASTA2V_CACHE_ROOT}/sources/LTX-2}"
export FASTA2V_LTX2_CHECKPOINT_ROOT="${FASTA2V_LTX2_CHECKPOINT_ROOT:-${FASTA2V_CACHE_ROOT}/checkpoints/ltx2.3}"
export FASTA2V_LTX2_RUN_ROOT="${FASTA2V_LTX2_RUN_ROOT:-${FASTA2V_CACHE_ROOT}/runs/ltx2}"
export FASTA2V_LTX2_GEMMA_ROOT="${FASTA2V_LTX2_GEMMA_ROOT:-${FASTA2V_CACHE_ROOT}/checkpoints/gemma-3-12b-it-qat-q4_0-unquantized}"
export FASTA2V_LTX2_PYTHON="${FASTA2V_LTX2_PYTHON:-/home/ma-user/.local/bin/python3.12}"

export CUDA_HOME="${FASTA2V_LTX2_CUDA_HOME:-/usr/local/cuda-12.8}"
export UV_PROJECT_ENVIRONMENT="${FASTA2V_LTX2_ENV}"
export UV_CACHE_DIR="${FASTA2V_LTX2_UV_CACHE_DIR:-${FASTA2V_CACHE_ROOT}/cache/uv-ltx2}"
export HF_HOME="${FASTA2V_LTX2_HF_HOME:-${FASTA2V_CACHE_ROOT}/cache/huggingface}"
export HF_HUB_CACHE="${FASTA2V_LTX2_HF_HUB_CACHE:-${HF_HOME}/hub}"
export TORCH_HOME="${FASTA2V_LTX2_TORCH_HOME:-${FASTA2V_CACHE_ROOT}/cache/torch-ltx2}"
export TORCH_EXTENSIONS_DIR="${FASTA2V_LTX2_TORCH_EXTENSIONS_DIR:-${FASTA2V_CACHE_ROOT}/cache/torch-extensions-ltx2}"
export PIP_CACHE_DIR="${FASTA2V_LTX2_PIP_CACHE_DIR:-${FASTA2V_CACHE_ROOT}/cache/pip-ltx2}"
export XDG_CACHE_HOME="${FASTA2V_LTX2_XDG_CACHE_HOME:-${FASTA2V_CACHE_ROOT}/cache/xdg-ltx2}"
export TMPDIR="${FASTA2V_LTX2_TMPDIR:-${FASTA2V_CACHE_ROOT}/cache/tmp-ltx2}"
export PYTHONNOUSERSITE=1

export PATH="${FASTA2V_LTX2_ENV}/bin:${CUDA_HOME}/bin:${PATH:-}"
if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
  export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"
else
  export LD_LIBRARY_PATH="${CUDA_HOME}/lib64"
fi

mkdir -p \
  "${FASTA2V_LTX2_CHECKPOINT_ROOT}" \
  "${FASTA2V_LTX2_RUN_ROOT}" \
  "${UV_CACHE_DIR}" \
  "${HF_HUB_CACHE}" \
  "${TORCH_HOME}" \
  "${TORCH_EXTENSIONS_DIR}" \
  "${PIP_CACHE_DIR}" \
  "${XDG_CACHE_HOME}" \
  "${TMPDIR}"
